---

jvmRouteName: "${jvm.route:noJvmRouteSet}"

proxy:
  connectors:
    http:
      port: 8080
    https:
      port: 8443
      sslProvider: OPENSSL
      sessionTimeoutMillis: 300000
      sessionCacheSize: 20000
      protocols:
        - TLSv1.2
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  bossThreadsCount: 1
  clientWorkerThreadsCount: 0
  workerThreadsCount: 0
  tcpNoDelay: true
  nioReuseAddress: true
  nioKeepAlive: true
  maxInitialLength: 8192
  maxHeaderSize: 65536
  maxChunkSize: 8192
  maxContentLength: 65536
  requestTimeoutMillis: 12000
  keepAliveTimeoutMillis: 120000
  maxConnectionsCount: 4000


admin:
  connectors:
    http:
      port: 9000
  bossThreadsCount: 1
  workerThreadsCount: 2
  tcpNoDelay: true
  nioReuseAddress: true
  nioKeepAlive: true
  maxInitialLength: 8192
  maxHeaderSize: 8192
  maxChunkSize: 8192
  maxContentLength: 65536

services:
  factories:
    backendServiceRegistry:
      class: "com.hotels.styx.proxy.backends.file.FileBackedBackendServicesRegistry$Factory"
      config:
        originsFile: "${originsFile:classpath:conf/origins.yml}"
    jmx:
      class: "com.hotels.styx.metrics.reporting.jmx.JmxReporterServiceFactory"
      config:
        domain: "com.hotels.styx"

retrypolicy:
  policy:
    factory:
      class: "com.hotels.styx.client.retry.RetryPolicyFactory"
      config: {count: 2}

loadBalancing:
  strategy:
    factory: {class: "com.hotels.styx.client.loadbalancing.strategies.PowerOfTwoStrategy$Factory"}

originRestrictionCookie: styx_origins

# Allow and Encode the list of unwise chars.
url:
  encoding:
    unwiseCharactersToEncode: "|,;,{,}"

logFormat: "vdomain=%v %t remote_host=%{True-Client-IP}i SiteSpectEngine=%{SiteSpect}i Akamai-Origin-Hop=%{Akamai-Origin-Hop}i AkamaiVia=\"%{Via}i\" X-AkamaiConfigLogDetail=\"%{X-Akamai-CONFIG-LOG-DETAIL}i\" forwarded_host=\"%{X-Forwarded-For}i\" ajax=%{X-Requested-With}i method_uri=\"%r\" statuscode=%>s redirect=%{Location}o bytes_sent=%b referer=\"%{Referer}i\" user_agent=\"%{User-Agent}i\" sessid=%{SESSID}C edgescape=\"%{X-Akamai-Edgescape}i\" guid=%{guid}C req_guid=%{X-Hcom-Info}o SSLB=\"%{SSLB}C\" X-hcom-ctx=\"%{X-hcom-ctx}o\"  duration_millis=%d scheme=\"%{SCHEME}e\" domain=\"%{Host}i\" X-Forwarded-Host=\"%{X-Forwarded-Host}i\" X-Forwarded-Server=\"%{X-Forwarded-Server}i\" X-NS-Forwarded-Server=\"%{X-NS-Forwarded-Server}i\" NetscalerFE=\"%{X-hcom-xinfo-NSFEVIP}i\" instance=%R url=%U retries=%N X-Hcom-Styx-Info=%{X-Hcom-Styx-Info}o"

request-logging:
  inbound:
    enabled: ${REQUEST_LOGGING_INBOUND_ENABLED:false}
    longFormat: ${REQUEST_LOGGING_INBOUND_LONG_FORMAT:false}
  outbound:
    enabled: ${REQUEST_LOGGING_OUTBOUND_ENABLED:false}
    longFormat: ${REQUEST_LOGGING_OUTBOUND_LONG_FORMAT:false}
