---

jvmRouteName: "${jvm.route:noJvmRouteSet}"

proxy:
  connectors:
    http:
      port: 8080
    https:
      port: 8443
      sslProvider: OPENSSL
      sessionTimeoutMillis: 300000
      sessionCacheSize: 20000
      protocols:
        - TLSv1.2
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  bossThreadsCount: 1
  clientWorkerThreadsCount: 0
  workerThreadsCount: 0
  tcpNoDelay: true
  nioReuseAddress: true
  nioKeepAlive: true
  maxInitialLength: 8192
  maxHeaderSize: 65536
  maxChunkSize: 8192
  maxContentLength: 65536
  requestTimeoutMillis: 12000
  keepAliveTimeoutMillis: 120000
  maxConnectionsCount: 4000


admin:
  connectors:
    http:
      port: 9000
  bossThreadsCount: 1
  workerThreadsCount: 2
  tcpNoDelay: true
  nioReuseAddress: true
  nioKeepAlive: true
  maxInitialLength: 8192
  maxHeaderSize: 8192
  maxChunkSize: 8192
  maxContentLength: 65536

services:
  factories:
    backendServiceRegistry:
      class: "com.hotels.styx.proxy.backends.file.FileBackedBackendServicesRegistry$Factory"
      config:
        originsFile: "${originsFile:classpath:conf/origins.yml}"
    jmx:
      class: "com.hotels.styx.metrics.reporting.jmx.JmxReporterServiceFactory"
      config:
        domain: "com.hotels.styx"

retrypolicy:
  policy:
    factory:
      class: "com.hotels.styx.client.retry.RetryPolicyFactory"
      config: {count: 2}

loadBalancing:
  strategy:
    factory: {class: "com.hotels.styx.client.loadbalancing.strategies.PowerOfTwoStrategy$Factory"}

originRestrictionCookie: styx_origins

# Allow and Encode the list of unwise chars.
url:
  encoding:
    unwiseCharactersToEncode: "|,;,{,}"

request-logging:
  inbound:
    enabled: ${REQUEST_LOGGING_INBOUND_ENABLED:false}
    longFormat: ${REQUEST_LOGGING_INBOUND_LONG_FORMAT:false}
  outbound:
    enabled: ${REQUEST_LOGGING_OUTBOUND_ENABLED:false}
    longFormat: ${REQUEST_LOGGING_OUTBOUND_LONG_FORMAT:false}
